# SuperBench Config
version: v0.12
superbench:
  enable: null
  monitor:
    enable: false
  var:
    default_local_mode: &default_local_mode
      enable: true
      modes:
        - name: local
          proc_num: 8
          prefix: HIP_VISIBLE_DEVICES={proc_rank}
          numactl:
            cpunodebind: gpu_affinity
            membind: gpu_affinity
          parallel: yes
    default_pytorch_mode: &default_pytorch_mode
      enable: false
      modes:
        - name: torch.distributed
          proc_num: 8
          node_num: 1
      frameworks:
        - pytorch
    common_model_config: &common_model_config
    model_ddp_parameter: &model_ddp_param
      duration: 0
      num_warmup: 128
      num_steps: 512
      sample_count: 8192
      batch_size: 128
      precision: [float32, float16]
      model_action: [train]
      pin_memory: yes
      num_workers: 0
    gpu_aware_mpi_mode: &gpu_aware_mpi_mode
      name: mpi
      node_num: 1
      bind_to: none
      mca:
        pml: ucx
        coll_hcoll_enable: 0
      env:
        UCX_TLS: self,sm,rocm
        UCX_MEMTYPE_CACHE: "n"
  benchmarks:
    kernel-launch:
      <<: *default_local_mode
    gemm-flops:
      <<: *default_local_mode
      parameters:
        precision:
          - fp64
          - fp32_xdlops
          - fp16_xdlops
          - bf16_xdlops
          - int8_xdlops
        shapes:
          - "4096:32768:2,8192,8192"
          - "4096:32768:2,8192,1024"
          - "4096:32768:2,1024,8192"
    hipblaslt-gemm:
      enable: true
      modes:
        - name: local
          proc_num: 8
          prefix: HIP_VISIBLE_DEVICES={proc_rank}
          parallel: yes
      parameters:
        in_types: [ "fp32", "fp16", "bf16" ]
        tolerant_fail: yes
        num_warmup: 100
        num_steps: 1000
        shapes:
          - 4096,4096,4096
          - 8192,8192,8192
          - 16384,16384,16384
    gpu-stream:
      enable: true
      modes:
        - name: local
          proc_num: 8
          prefix: HIP_VISIBLE_DEVICES={proc_rank}
          parallel: yes
      parameters:
        array_size: 268435456
        num_loops: 100
        precision: double
    rccl-bw:allreduce-r8:
      enable: true
      modes:
        - name: mpi
          proc_num: 8
          node_num: 1
          bind_to: none
          env:
            NCCL_BUFFSIZE: 4194304
      parameters:
        maxbytes: 16G
        ngpus: 1
        operation: allreduce
    rccl-bw:allreduce-r8-pcie:
      enable: true
      modes:
        - name: mpi
          proc_num: 8
          node_num: 1
          bind_to: none
          env:
            NCCL_BUFFSIZE: 4194304
            NCCL_SIMPLE_CHANNELS: 32
            RCCL_P2P_XHCL_CHANNEL_NUM: 31
            RCCL_COLL_XHCL_CHANNEL_NUM: 28
      parameters:
        maxbytes: 16G
        ngpus: 1
        operation: allreduce
    rccl-bw:alltoall-r8:
      enable: true
      modes:
        - name: mpi
          proc_num: 8
          node_num: 1
          bind_to: none
      parameters:
        maxbytes: 16G
        ngpus: 1
        operation: alltoall
    gpu-hpl:r8:
      enable: false
      modes:
        - <<: *gpu_aware_mpi_mode
          proc_num: 8
      parameters:
        p: 4
        q: 2
        n: 368640
        nb: 512
        bcast: 1
        warmup: 1
        iterations: 3
    gpu-hpl:r4:
      enable: false
      modes:
        - <<: *gpu_aware_mpi_mode
          proc_num: 4
      parameters:
        p: 4
        q: 1
        n: 260096
        nb: 512
        bcast: 1
        warmup: 1
        iterations: 3
    gpu-hpl:r2:
      enable: false
      modes:
        - <<: *gpu_aware_mpi_mode
          proc_num: 2
      parameters:
        p: 2
        q: 1
        n: 185344
        nb: 512
        bcast: 1
        warmup: 1
        iterations: 3
    gpu-hpl:r1:
      enable: false
      modes:
        - name: mpi
          proc_num: 1
          node_num: 1
          bind_to: none
      parameters:
        p: 1
        q: 1
        n: 131072
        nb: 512
        nbmin: 16
        bcast: 1
        warmup: 1
        iterations: 3
    gpu-hpl-mxp:r8:
      enable: false
      modes:
        - <<: *gpu_aware_mpi_mode
          proc_num: 8
      parameters:
        p: 2
        q: 4
        n: 524288
        nb: 4096
        bcast: 1
        warmup: 1
        iterations: 3
    gpu-hpl-mxp:r4:
      enable: false
      modes:
        - <<: *gpu_aware_mpi_mode
          proc_num: 4
      parameters:
        p: 2
        q: 2
        n: 360448
        nb: 4096
        bcast: 1
        warmup: 1
        iterations: 3
    gpu-hpl-mxp:r2:
      enable: false
      modes:
        - <<: *gpu_aware_mpi_mode
          proc_num: 2
      parameters:
        p: 1
        q: 2
        n: 262144
        nb: 4096
        bcast: 1
        warmup: 1
        iterations: 3
    gpu-hpl-mxp:r1:
      enable: false
      modes:
        - name: mpi
          proc_num: 1
          node_num: 1
          bind_to: none
      parameters:
        p: 1
        q: 1
        n: 184320
        nb: 4096
        bcast: 1
        warmup: 1
        iterations: 3
    gpu-hpcg:r8:
      enable: false
      modes:
        - <<: *gpu_aware_mpi_mode
          proc_num: 8
      parameters:
        nx: 560
        ny: 280
        nz: 280
        rt: 1
        npx: 2
        npy: 2
        npz: 2
    gpu-hpcg:r4:
      enable: false
      modes:
        - <<: *gpu_aware_mpi_mode
          proc_num: 4
      parameters:
        nx: 560
        ny: 280
        nz: 280
        rt: 1
        npx: 2
        npy: 2
        npz: 1
    gpu-hpcg:r2:
      enable: false
      modes:
        - <<: *gpu_aware_mpi_mode
          proc_num: 2
      parameters:
        nx: 560
        ny: 280
        nz: 280
        rt: 1
        npx: 2
        npy: 1
        npz: 1
    gpu-hpcg:r1:
      enable: false
      modes:
        - name: mpi
          proc_num: 1
          node_num: 1
          bind_to: none
      parameters:
        nx: 560
        ny: 280
        nz: 280
        rt: 1
        npx: 1
        npy: 1
        npz: 1
    cpu-memory-bw-latency:
      enable: false
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        tests:
          - bandwidth_matrix
          - latency_matrix
          - max_bandwidth
    mem-bw:
      enable: true
      modes:
        - name: local
          proc_num: 8
          prefix: HIP_VISIBLE_DEVICES={proc_rank}
          parallel: no
    ib-loopback:
      enable: false
      modes:
        - name: local
          proc_num: 16
          prefix: PROC_RANK={proc_rank} IB_DEVICES=0,1,2,3,4,5,6,7,0,1,2,3,4,5,6,7 numactl -N $(({proc_rank}/8)) -m $(({proc_rank}/8))
          parallel: no
      parameters:
        msg_size: 8388608
    disk-benchmark:
      enable: false
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        block_devices: []
    gpu-copy-bw:correctness:
      enable: true
      modes:
        - name: local
          parallel: no
      parameters:
        mem_type: [htod, dtoh, dtod, one_to_all, all_to_one, all_to_all]
        copy_type: [sm, dma]
        size: 4096
        num_warm_up: 0
        num_loops: 1
        check_data: true
    gpu-copy-bw:perf:
      enable: true
      modes:
        - name: local
          parallel: no
      parameters:
        mem_type: [htod, dtoh, dtod, one_to_all, all_to_one, all_to_all]
        copy_type: [sm, dma]
        num_warm_up: 20
        num_loops: 10
    dist-inference:
      modes:
      - name: mpi
        proc_num: 8
        node_num: 1
      frameworks:
        - pytorch
      parameters:
        num_layers: 20
        num_warmup: 20
        num_steps: 100
        use_cuda_graph: true
        precision: float16
        hidden_size: 4096
        input_size: 4096
        batch_size: 1024
    ort-inference:
      <<: *default_local_mode
      parameters:
        execution_provider: rocm
        pytorch_models:
          - resnet50
          - resnet152
          - resnext50_32x4d
          - wide_resnet50_2
          - mobilenet_v2
        precision: float16
        batch_size: 1
    computation-communication-overlap:
      <<: *default_pytorch_mode
    sharding-matmul:
      <<: *default_pytorch_mode
